// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMVVpAlEQfi3hbzGwl-jZQZuaz785Zim4',
    appId: '1:746595275459:web:4a67314db5047b1673c876',
    messagingSenderId: '746595275459',
    projectId: 'maham-project-1',
    authDomain: 'maham-project-1.firebaseapp.com',
    storageBucket: 'maham-project-1.appspot.com',
    measurementId: 'G-MYFTC3DS7C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQF6OW9srjnKZ6YatMNd2oCIOFDkJiOFw',
    appId: '1:746595275459:android:047df86c14a10ea973c876',
    messagingSenderId: '746595275459',
    projectId: 'maham-project-1',
    storageBucket: 'maham-project-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfkEtMFVeaBu84TvfSAmn3swHm-VHEuWM',
    appId: '1:746595275459:ios:82c1f4e8052dc8ff73c876',
    messagingSenderId: '746595275459',
    projectId: 'maham-project-1',
    storageBucket: 'maham-project-1.appspot.com',
    iosBundleId: 'com.example.mtrack',
  );
}
